package com.systech.mss.domain;

public enum Status {
    PENDING,
    APPROVED,
    DECLINED,
    AUTHORIZED,
    UPLOADED,
    NOT_UPLOADED,
    DECLINED_BY_CRM,
    DECLINED_BY_SPONSOR,
    PUSHED_TO_FUNDMASTER,
    CERTIFIED,
    AUTHORIZED_BY_CRM,
    EDITED,
    APPROVED_BY_MEMBER
}
